version: "3.9"

services:
  db:
    image: postgres:15
    container_name: device-service-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: device-user
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: device-db
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
